name: app
type: "php:7.4"

relationships:
    database: "db:mysql"

web:
    locations:
        "/":
            root: "wordpress"
            passthru: "/index.php"
            index:
                - "index.php"
            expires: 700
            scripts: true
            allow: true
            rules:
                ^/composer\.json:
                    allow: false
                ^/license\.txt$:
                    allow: false
                ^/readme\.html$:
                    allow: false
        "/wp-content/cache":
            root: "wordpress/wp-content/cache"
            scripts: false
            allow: false
        "/wp-content/uploads":
            root: "wordpress/wp-content/uploads"
            scripts: false
            allow: true

disk: 2048
dependencies:
    php:
        wp-cli/wp-cli: "^2.2.0"
        psy/psysh: "^0.8.4"

mounts:
    "wordpress/wp-content/cache":
        source: local
        source_path: "cache"
    "wordpress/wp-content/uploads":
        source: local
        source_path: "uploads"

source:
    operations:
        upstream-update:
            command: |
                set -e
                git remote add upstream $UPSTREAM_REMOTE
                git fetch --all
                git merge upstream/master
